name: publish
on:
  create: # when tags are created
  push:
    branches:
      - "*" # Default release branch, may also be named 'master' or 'develop'
  workflow_dispatch:
    # allow manual trigger

jobs:
  windows_latest:
    name: build, pack & publish
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Restore dependencies
        run: dotnet restore ClickableTransparentOverlay

      - name: Build Project
        run: dotnet build -c Release --no-restore ClickableTransparentOverlay

      - name: Packages Project
        run: dotnet pack ClickableTransparentOverlay/ClickableTransparentOverlay.csproj -c Release --no-restore --no-build

      - name: Build Demo for Github
        run: |
          dotnet build -c Release Examples/MultiThreadedOverlay
          tar -a -v -c -f demo.zip Examples\MultiThreadedOverlay\bin\Release

      - name: Upload
        uses: actions/upload-artifact@v4.3.5
        with:
          path: demo.zip
